### ISSUE TITLE
Setting properties on awakeFromNib

### ISSUE THREAD

**Issue by miguelrc86** [HeshamMegid/HMSegmentedControl#145]
Hi Hesham!

First of all, amazing replacement for UISegmentedControl, I loved your work... but...

I threw an UIView on a custom UITableViewCell Xib, set its class to HMSegmentedControl, made a connection with the custom cell header, and I was trying to customize the control on the awakeFromNib method of the cell, and some properties seems to work, but others just don't... no matter what I tried.. I couldn't set the background color of the HMSegmentedControl or the selectionIndicatorLocation for example... but when I dequeue the cell on my TableViewController, I gave it another try and I was able to do it... I would like to know if I'm missing something here or if this is really an issue...

I used Xcode 7, Obj-C, and tested it on ios 7 / 8 / 9

Thanks!

**Comment by federicocappelli** [comment]
the problem here is that the **commonInit** method is called multiple time in HMSegmentedControl, even from the **awakeFromNib** that is naturally called after the cell **awakeFromNib**, thats bring the component to overwrite all the settings just set in the cell awakeFromNib.

Pull request submitted: https://github.com/HeshamMegid/HMSegmentedControl/pull/159

**Comment by HeshamMegid** [comment]
That issue has been fixed on the latest version.
